trigger:
- main

pool:
  name: Default  # Dein Self-hosted Agent Pool mit Zugriff auf C:\apano_Dienste

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  projectName: 'KafkaConsumerService'
  targetPath: 'C:\apano_Dienste\KafkaConsumerService'

steps:

# NuGet wiederherstellen
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# Projekt kompilieren
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Projekt veröffentlichen
- script: dotnet publish -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish project'

# Zielordner erstellen (falls nicht vorhanden)
- powershell: |
    if (-Not (Test-Path -Path "$(targetPath)")) {
        New-Item -ItemType Directory -Path "$(targetPath)" | Out-Null
        Write-Host "Zielverzeichnis erstellt: $(targetPath)"
    } else {
        Write-Host "Zielverzeichnis vorhanden: $(targetPath)"
    }
  displayName: 'Ensure target directory exists'

# Dateien ins Zielverzeichnis kopieren
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '**'
    TargetFolder: '$(targetPath)'
  displayName: 'Copy published EXE to deployment folder'

# Inhalt auflisten zur Kontrolle (optional)
- powershell: |
    Write-Host "Inhalt von $(targetPath):"
    Get-ChildItem -Path "$(targetPath)" -Recurse
  displayName: 'List deployed files'
